### PR TITLE
Fix: TPC icon is not visible in the Gutenberg editor with WP 6.4

### LINKED ISSUE #309: [WP 6.4] TPC icon is not visible in the Gutenberg editor
### Description

After updating to WP 6.4 RC2, the TPC icon [is not visible](https://vertis.d.pr/v/GA27tv) in the Gutenberg editor and a [console error](https://vertis.d.pr/i/NazAtC) is thrown. If Neve is installed & activated, it works fine

### Step-by-step reproduction instructions

1. Install WordPress 6.4 RC2
2. Install TPC only (without Neve)
3. Open the editor and check if the TPC icon is visible

### Screenshots, screen recording, code snippet or Help Scout ticket

Video - https://vertis.d.pr/v/GA27tv
Console error - https://vertis.d.pr/i/NazAtC

### Environment info

WordPress 6.4 RC2 / PHP 8 / TPC 1.2.5

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Removed the `omit` requirement that was used from `lodash` and replaced it with a native spread operation instead.

Notes:
`lodash` was used from Neve and never packaged as part of this plugin, previously it would default to using the `lodash` from WP, but was removed for the newer versions of WordPress.
Since we only use the `omit` function, I think it can be safely removed and replaced with a native function already available in JS.

### Test instructions

<details open>
    <summary><h4>Testing with WP 6.4</h4></summary>

1. Install WordPress 6.4 RC2 using [WordPress Beta Release](https://wordpress.org/plugins/wordpress-beta-tester/)
2. Install TPC only (without Neve), and **Activate it** using a valid key.
3. Open the editor and check if the TPC icon is visible
    image
4. Check that it works as before when Neve is enabled.
</details>

<details>
    <summary><h4>Testing with WP 6.3.2 or current version</h4></summary>

1. Install TPC only (without Neve), and **Activate it** using a valid key.
2. Open the editor and check if the TPC icon is visible the same as on the previous test.
3. Check that it works as before when Neve is enabled.
</details>

Closes #309.

### CODE REVIEW

File: editor/src/extension.js [hunk 1]
```diff
@@ -182,10 +180,15 @@ const Exporter = () => {
 			content,
 		};
 
+		const { meta, ...filteredParams } = window.tiTpc.params;
+		console.log( { meta, filteredParams } );
+		console.log( tiTpc.params );
+		return;
```
Comment (HardeepAsrani) [inline editor/src/extension.js:186]: Not sure if this was meant for the commit?

**Review by HardeepAsrani — COMMENTED** [review]
Hey @preda-bogdan,

While the code looks good, we can use an easier solution. The lodash is still part of WordPress core in 6.4 as far as I'm aware, and we could've replaced:

`const { omit } = lodash;`

with 

`import { omit } from 'lodash';`

And it would've worked as far as I'm aware. At the same time, I'm not against removing lodash for ES6 language features.

File: editor/src/extension.js (hunk 1 above)
Comment (preda-bogdan) [reply editor/src/extension.js]: Thank you for that, I did not push the cleanup changes, I'm sorry for that. Should be good now.

**Comment by preda-bogdan** [comment]
@HardeepAsrani, since we are only using `lodash` for the `omit` function and the same can be achieved with native code, I don't see the reason for having this as an extra dependency to worry about. I'm pretty sure this is intended to be removed in the future and we can try to not rely on external dependencies that we do not intend to bundle if not required. 

Let me know what you think about this. Thank you!

**Review by HardeepAsrani — APPROVED** [review]
Thanks for the cleanup.

**Comment by irinelenache** [comment]
@preda-bogdan Tested and the issue is fixed now, thank you 🚀
